version: '3.4'

services:
  unwinder-api:
    image: node-typescript-express-docker-starter
    volumes: 
      - "files:/usr/src/app/files"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
volumes:
  files: