version: '3.4'

services:
  express-api:
    image: node-typescript-express-docker-starter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
