version: '3.4'

services:
  express-api:
    image: node-typescript-express-docker-starter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./dist/bin/www.js"]
